language: c++

os:
    - linux
#    - osx

sudo: required
dist: trusty

compiler:
    - gcc
    - clang

# Mapnik doesn't have a stable 3.0.x release in PPA. Nightly has problems with input plugins.
# I don't want to build Mapnik from source here for time and hassle reasons... so I'm cheating.
#
#env:
#    - REPORT_EXIT_STATUS=1

before_install:
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install icu4c; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mapnik; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/php/php70; fi

    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install python-software-properties; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ondrej/php; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository -y ppa:mapnik/nightly-trunk; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y purge php5-fpm; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install file php7.0-cli php7.0 php7.0-common php7.0-gd php7.0-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install libmapnik mapnik-utils libmapnik-dev; fi

script:
    - phpize
    - ./configure --with-mapnik
    - make test

after_failure:
    - tail -n 1000 tests/*.log
